apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: s3-cleaner-role
  namespace: s3-cleaner
rules:
  # Allow the controller to manage CronJobs
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Allow the controller to read/write Secrets (for mounting rclone configs)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
